import {Group} from "../models/group";
const groups: Group[] =
  [{"id":1,"name":"Product Design and Development"},
    {"id":2,"name":"Graphic Illustration"},
    {"id":3,"name":"Corporate Communications Strategy and Execution"},
    {"id":4,"name":"Strategic Consulting and Advisory"},
    {"id":5,"name":"Business Continuity Planning"},
    {"id":6,"name":"Business Analytics and Insights"},
    {"id":7,"name":"Sales Training"},
    {"id":8,"name":"Business Development and Growth Strategy"},
    {"id":9,"name":"Payroll Processing"},
    {"id":10,"name":"Product Launch"},
    {"id":11,"name":"Inventory Control and Auditing Services"},
    {"id":12,"name":"Competitive Market Analysis"},
    {"id":13,"name":"Business Planning and Strategy"},
    {"id":14,"name":"Research and Development"},
    {"id":15,"name":"Social Media Advertising and Management"},
    {"id":16,"name":"Vendor Negotiation"},
    {"id":17,"name":"Employee Recognition Programs"},
    {"id":18,"name":"Vendor Selection and Negotiation Services"},
    {"id":19,"name":"Vendor Relationship Management"},
    {"id":20,"name":"Inventory Control"},
    {"id":21,"name":"Corporate Event Planning"},
    {"id":22,"name":"Tax Planning and Preparation Services"},
    {"id":23,"name":"Competitive Analysis"},
    {"id":24,"name":"CRM Implementation"},
    {"id":25,"name":"Sales Forecasting and Planning"},
    {"id":26,"name":"Event Marketing and Promotion Services"},
    {"id":27,"name":"Business Development"},
    {"id":28,"name":"Supply Chain Optimization and Efficiency"},
    {"id":29,"name":"Creative Team"},
    {"id":30,"name":"Legal Compliance and Regulations"},
    {"id":31,"name":"Legal Compliance and Regulations Consulting"},
    {"id":32,"name":"Public Relations Management and Strategy"},
    {"id":33,"name":"Accounting Software Management Services"},
    {"id":34,"name":"Tax Planning and Preparation Services"},
    {"id":35,"name":"Inventory Control and Auditing"},
    {"id":36,"name":"Sales Forecasting and Planning"},
    {"id":37,"name":"Corporate Communications Strategy"},
    {"id":38,"name":"Corporate Event Planning"},
    {"id":39,"name":"Legal Compliance"},
    {"id":40,"name":"Product Design"},
    {"id":41,"name":"Business Continuity"},
    {"id":42,"name":"Employee Relations Management and Support"},
    {"id":43,"name":"Workers"},
    {"id":44,"name":"Database Administration and Management"},
    {"id":45,"name":"Customer Acquisition and Retention"},
    {"id":46,"name":"Database Administration and Management"},
    {"id":47,"name":"Cleaning Ladies"},
    {"id":48,"name":"Corporate Culture Building"},
    {"id":49,"name":"Corporate Events"},
    {"id":50,"name":"Business Continuity Planning and Management"},
    {"id":51,"name":"Public Relations Management and Strategy"},
    {"id":52,"name":"Strategic Alliances and Partnerships"},
    {"id":53,"name":"Product Launch"},
    {"id":54,"name":"Tax Compliance"},
    {"id":55,"name":"Corporate Communications"},
    {"id":56,"name":"Accounting Department"},
    {"id":57,"name":"Vendor Negotiation"},
    {"id":58,"name":"Inventory Tracking and Management"},
    {"id":59,"name":"Website Design"},
    {"id":60,"name":"Customer Acquisition and Retention Services"},
    {"id":61,"name":"Inventory Control and Auditing"},
    {"id":62,"name":"Social Media Management"},
    {"id":63,"name":"Public Policy Advocacy and Lobbying"},
    {"id":64,"name":"Data Entry and Analysis"},
    {"id":65,"name":"Graphic Design and Branding Services"},
    {"id":66,"name":"Employee Recognition"},
    {"id":67,"name":"Sales Operations"},
    {"id":68,"name":"Data Analysis and Reporting"},
    {"id":69,"name":"Website Maintenance"},
    {"id":70,"name":"Corporate Event Planning"},
    {"id":71,"name":"Social Media Team"},
    {"id":72,"name":"Event Marketing"},
    {"id":73,"name":"Web Development and Design"},
    {"id":74,"name":"Customer Acquisition"},
    {"id":75,"name":"Training Program Development and Implementation Services"},
    {"id":76,"name":"Strategic Consulting and Advisory"},
    {"id":77,"name":"Public Affairs"},
    {"id":78,"name":"Customer Data Management and Analysis Services"},
    {"id":79,"name":"Tax Planning and Preparation"},
    {"id":80,"name":"Inventory Control and Auditing Services"},
    {"id":81,"name":"Database Administration and Management Services"},
    {"id":82,"name":"Social Media Team"},
    {"id":83,"name":"Website Design"},
    {"id":84,"name":"Warehouse Staff"},
    {"id":85,"name":"Strategic Consulting"},
    {"id":86,"name":"Logistics Coordination"},
    {"id":87,"name":"Brand Development and Strategy Services"},
    {"id":88,"name":"Employee Benefits"},
    {"id":89,"name":"Product Launch"},
    {"id":90,"name":"Product Launch Planning and Execution Services"},
    {"id":91,"name":"Sales Training"},
    {"id":92,"name":"Public Relations Strategy"},
    {"id":93,"name":"Procurement Team"},
    {"id":94,"name":"Accounting Software"},
    {"id":95,"name":"Account Reconciliation and Reporting Services"},
    {"id":96,"name":"Social Media Marketing and Advertising Services"},
    {"id":97,"name":"Corporate Governance"},
    {"id":98,"name":"Inventory Tracking"},
    {"id":99,"name":"Database Administration and Management Services"},
    {"id":100,"name":"Event Coordination"}];

export { groups };
